[package]
name = "aec"
version = "0.1.0"
edition = "2024"

[features]
default = ["onnx", "128"]
onnx = ["dep:skald-onnx"]
128 = []
256 = []
512 = []

[dependencies]
skald-onnx = { workspace = true, optional = true }

realfft = { workspace = true }

serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
clap = { workspace = true, features = ["derive"] }
criterion = { workspace = true }
dasp = { workspace = true }
hound = { workspace = true }
rodio = { workspace = true }
skald-audacity = { workspace = true }
skald-audio-snapshot = { workspace = true }
skald-audio-utils = { workspace = true }

[[bench]]
name = "aec_bench"
harness = false
