[package]
name = "api-messenger"
version = "0.1.0"
edition = "2024"

[dependencies]
skald-api-error = { workspace = true }
skald-http = { workspace = true }
skald-slack-web = { workspace = true }
skald-teems = { workspace = true }

axum = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
