[package]
name = "audio-norm"
version = "0.1.0"
edition = "2024"

[dependencies]
audioadapter-buffers = "2.0"
notiz-afconvert = { workspace = true }
notiz-audio-utils = { workspace = true }
notiz-mp3 = { workspace = true }
notiz-resampler = { workspace = true }

rodio = { workspace = true, features = ["symphonia-all"] }
thiserror = { workspace = true }

[dev-dependencies]
assert_fs = "1"
notiz-data = { workspace = true }
