[package]
name = "vad-masking"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
clap = { workspace = true, features = ["derive"] }
hound = { workspace = true }
rodio = { workspace = true }
skald-audacity = { workspace = true }
skald-data = { workspace = true }

[dependencies]
skald-audio-utils = { workspace = true }
skald-vad = { workspace = true, features = ["earshot"] }
