[package]
name = "local-model"
version = "0.1.0"
edition = "2024"

[dependencies]
notiz-am = { workspace = true }
notiz-file = { workspace = true }
notiz-model-downloader = { workspace = true }
notiz-transcribe-soniqo = { workspace = true }
notiz-whisper-local-model = { workspace = true }

serde = { workspace = true }
specta = { workspace = true }
tracing = { workspace = true }
