[package]
name = "ws-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
owhisper-interface = { workspace = true }
skald-audio-utils = { workspace = true }

axum = { workspace = true, features = ["ws"] }
serde_json = { workspace = true }
skald-audio-interface = { workspace = true }

futures-util = { workspace = true }
pin-project = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
