[package]
name = "api-ticket"
version = "0.1.0"
edition = "2024"

[dependencies]
notiz-api-auth = { workspace = true }
notiz-api-error = { workspace = true }
notiz-api-nango = { workspace = true }
notiz-github-issues = { workspace = true, features = ["utoipa"] }
notiz-linear = { workspace = true }
notiz-nango = { workspace = true }
notiz-ticket-interface = { workspace = true, features = ["utoipa"] }

axum = { workspace = true }
utoipa = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
