[package]
name = "api-ticket"
version = "0.1.0"
edition = "2024"

[dependencies]
skald-api-auth = { workspace = true }
skald-api-error = { workspace = true }
skald-api-nango = { workspace = true }
skald-github-issues = { workspace = true, features = ["utoipa"] }
skald-linear = { workspace = true }
skald-nango = { workspace = true }
skald-ticket-interface = { workspace = true, features = ["utoipa"] }

axum = { workspace = true }
utoipa = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
