[package]
name = "api-mail"
version = "0.1.0"
edition = "2024"

[dependencies]
skald-api-auth = { workspace = true }
skald-api-error = { workspace = true }
skald-api-nango = { workspace = true }
skald-google-mail = { workspace = true, features = ["utoipa"] }
skald-nango = { workspace = true }

axum = { workspace = true }
utoipa = { workspace = true }

serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
